#pragma once

#include "CoreMinimal.h"
#include "EditorSubsystem.h"
#include "SplineGenerator.h"
#include "SignalGenerator.h"
#include "OpenDriveEditorSubsystem.generated.h"

class USignalTypeMapping;
class UOpenDriveAsset;

/**
 * Editor subsystem for OpenDRIVE scripting.
 * Exposes spline and signal generation to Blueprint and Python.
 *
 * Python usage:
 *   import unreal
 *   subsystem = unreal.get_editor_subsystem(unreal.OpenDriveEditorSubsystem)
 *   subsystem.generate_lane_splines()
 */
UCLASS(BlueprintType)
class OPENDRIVEEDITOR_API UOpenDriveEditorSubsystem : public UEditorSubsystem
{
	GENERATED_BODY()

public:

	// ==========================================
	// OpenDRIVE Asset Setup
	// ==========================================

	/**
	 * Sets the OpenDRIVE asset on the current World Settings and loads it into RoadManager.
	 * @param Asset The OpenDriveAsset to assign (e.g. loaded via unreal.load_asset())
	 * @return true if successfully set and loaded
	 */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Setup")
	bool SetOpenDriveAsset(UOpenDriveAsset* Asset);

	/**
	 * Gets the currently assigned OpenDRIVE asset from World Settings.
	 * @return The current OpenDriveAsset, or nullptr if none is set
	 */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Setup")
	UOpenDriveAsset* GetOpenDriveAsset();

	// ==========================================
	// Spline Generation
	// ==========================================

	/** Generates lane spline actors from OpenDRIVE road data. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void GenerateLaneSplines();

	/** Clears all spline actors generated by this subsystem. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void ClearGeneratedSplines();

	/** Sets the Z-offset for spline generation (in cm). Default: 20. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetSplineOffset(float Offset);

	/** Sets the step distance for spline point generation (in meters). Lower = more precise. Default: 5. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetSplineStep(float Step);

	/** Sets the spline generation mode: 0=Center, 1=Inside, 2=Outside. Default: 0. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetSplineMode(int32 Mode);

	/** Enables/disables generation of road lanes (non-junction). Default: true. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetGenerateRoads(bool bGenerate);

	/** Enables/disables generation of junction lanes. Default: true. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetGenerateJunctions(bool bGenerate);

	/** Sets all lane type filters at once. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetLaneTypeFilter(
		bool bDriving,
		bool bSidewalk,
		bool bBiking,
		bool bParking,
		bool bShoulder,
		bool bRestricted,
		bool bMedian,
		bool bOther,
		bool bReference);

	/** If true, only generates the outermost driving lane per side. Default: false. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetGenerateOutermostDrivingLaneOnly(bool bOutermostOnly);

	// ==========================================
	// Signal Generation
	// ==========================================

	/** Generates signal actors from OpenDRIVE data using the given mapping asset. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Signals")
	void GenerateSignals(USignalTypeMapping* MappingAsset);

	/** Clears all signal actors generated by this subsystem. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Signals")
	void ClearGeneratedSignals();

	/** If true, flips signal orientation by 180 degrees. Default: false. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Signals")
	void SetFlipSignalOrientation(bool bFlip);

private:

	FSplineGenerator SplineGen;
	FSignalGenerator SignalGen;
};
