#pragma once

#include "CoreMinimal.h"
#include "EditorSubsystem.h"
#include "SplineGenerator.h"
#include "SignalGenerator.h"
#include "RoadMeshGenerator.h"
#include "OpenDriveEditorSubsystem.generated.h"

class USignalTypeMapping;
class UOpenDriveAsset;

/**
 * Editor subsystem for OpenDRIVE scripting.
 * Exposes spline and signal generation to Blueprint and Python.
 *
 * Python usage:
 *   import unreal
 *   subsystem = unreal.get_editor_subsystem(unreal.OpenDriveEditorSubsystem)
 *   subsystem.generate_lane_splines()
 */
UCLASS(BlueprintType)
class OPENDRIVEEDITOR_API UOpenDriveEditorSubsystem : public UEditorSubsystem
{
	GENERATED_BODY()

public:

	// ==========================================
	// OpenDRIVE Asset Setup
	// ==========================================

	/**
	 * Sets the OpenDRIVE asset on the current World Settings and loads it into RoadManager.
	 * @param Asset The OpenDriveAsset to assign (e.g. loaded via unreal.load_asset())
	 * @return true if successfully set and loaded
	 */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Setup")
	bool SetOpenDriveAsset(UOpenDriveAsset* Asset);

	/**
	 * Gets the currently assigned OpenDRIVE asset from World Settings.
	 * @return The current OpenDriveAsset, or nullptr if none is set
	 */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Setup")
	UOpenDriveAsset* GetOpenDriveAsset();

	// ==========================================
	// Spline Generation
	// ==========================================

	/** Generates lane spline actors from OpenDRIVE road data. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void GenerateLaneSplines();

	/** Clears all spline actors generated by this subsystem. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void ClearGeneratedSplines();

	/** Sets the Z-offset for spline generation (in cm). Default: 20. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetSplineOffset(float Offset);

	/** Sets the step distance for spline point generation (in meters). Lower = more precise. Default: 5. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetSplineStep(float Step);

	/** Sets the spline generation mode: 0=Center, 1=Inside, 2=Outside. Default: 0. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetSplineMode(int32 Mode);

	/** Enables/disables generation of road lanes (non-junction). Default: true. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetGenerateRoads(bool bGenerate);

	/** Enables/disables generation of junction lanes. Default: true. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetGenerateJunctions(bool bGenerate);

	/** Sets all lane type filters at once. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetLaneTypeFilter(
		bool bDriving,
		bool bSidewalk,
		bool bBiking,
		bool bParking,
		bool bShoulder,
		bool bRestricted,
		bool bMedian,
		bool bOther,
		bool bReference);

	/** If true, only generates the outermost driving lane per side. Default: false.
	 *  (Backward-compatible; internally maps to SetLanePositionFilter(2).) */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetGenerateOutermostDrivingLaneOnly(bool bOutermostOnly);

	/** Enables/disables generation of left lanes (ID > 0). Default: true. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetGenerateLeftLanes(bool bGenerate);

	/** Enables/disables generation of right lanes (ID < 0). Default: true. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetGenerateRightLanes(bool bGenerate);

	/**
	 * Sets the lane position filter mode.
	 * 0 = All, 1 = Outermost Only (all types), 2 = Outermost Driving Only,
	 * 3 = Innermost Only (all types), 4 = Innermost Driving Only, 5 = Specific Index
	 */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetLanePositionFilter(int32 FilterMode);

	/** Sets the specific lane index (1-based from center). Only used when filter mode = 5. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Splines")
	void SetSpecificLaneIndex(int32 Index);

	// ==========================================
	// Road Mesh Generation
	// ==========================================

	/** Loads an OpenDRIVE .xodr file directly into the roadmanager (bypasses WorldSettings). Test helper. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	bool LoadXodrFile(const FString& AbsoluteFilePath);

	/** Generates the road mesh (UDynamicMeshComponent based ARoadMeshActor) from the loaded OpenDRIVE. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	FString GenerateRoadMesh();

	/** Destroy any previously generated ARoadMeshActor. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void ClearGeneratedRoadMeshes();

	/** Set the maximum step (m) for s-sampling. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshMaxStep(float MaxStepMeters);

	/** Set the Z offset (cm) added to the road surface. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshZOffset(float ZOffsetCm);

	/** Set the Z offset (cm) for road markings above the road surface (default 0.05). */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshMarkingZOffset(float MarkingZOffsetCm);

	/** Toggle generation of road markings. Default: true. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshGenerateMarkings(bool bGenerate);

	/** Toggle generation of junction fill patches. Default: true. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshGenerateJunctionPatches(bool bGenerate);

	/** Toggle generation of non-driving lane surfaces (sidewalk/border/shoulder/...). Default: true. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshGenerateNonDrivingLanes(bool bGenerate);

	/** Set the raised-curb height (cm). 0 = flat surface, no curb step. Default: 15. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshCurbHeight(float CurbHeightCm);

	/** Set the at-grade road slab thickness (cm). 0 = paper-thin ribbon. Default: 50. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshRoadThickness(float RoadThicknessCm);

	/** Toggle the overpass deck structure (slab + parapets + piers on elevated spans). Default: false. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshGenerateDeckStructure(bool bGenerate);

	/** Set all overpass-deck numeric parameters at once (cm/m as per each field). */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshDeckParams(
		float DeckHeightThresholdMeters,
		float GroundZCm,
		float DeckThicknessCm,
		float ParapetHeightCm,
		float ParapetThicknessCm,
		float PierSpacingMeters,
		float PierHalfWidthCm,
		float PierRoadClearanceMeters);

	/** Assign material slot 0..N for ERoadMeshMaterialSlot. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshMaterials(const TArray<UMaterialInterface*>& Materials);

	/** Override the Content folder used for auto-discovery (default: /Game/RoadGeneration/Material). */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void SetRoadMeshMaterialFolder(const FString& ContentPath);

	/** Enable complex-as-simple collision on every generated road mesh actor. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	void EnableRoadMeshCollision();

	/**
	 * Bake the most recently generated road mesh actor's DynamicMesh into a UStaticMesh asset.
	 * @param AssetPath Package path including asset name, e.g. "/Game/Roads/SM_Road"
	 * @return The created asset (or nullptr).
	 */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|RoadMesh")
	class UStaticMesh* BakeRoadMeshToStaticMesh(const FString& AssetPath);

	// ==========================================
	// Signal Generation
	// ==========================================

	/** Generates signal actors from OpenDRIVE data using the given mapping asset. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Signals")
	void GenerateSignals(USignalTypeMapping* MappingAsset);

	/** Clears all signal actors generated by this subsystem. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Signals")
	void ClearGeneratedSignals();

	/** If true, flips signal orientation by 180 degrees. Default: false. */
	UFUNCTION(BlueprintCallable, Category = "OpenDRIVE|Signals")
	void SetFlipSignalOrientation(bool bFlip);

private:

	FSplineGenerator SplineGen;
	FSignalGenerator SignalGen;
	FRoadMeshGenerator MeshGen;
};
